/**
 * Block DNA legacy resolver contract.
 *
 * WHY THIS FILE EXISTS
 * The generic resolver picks a DNA by indexing into catalog-derived arrays
 * (`seedNum % matches.length`, nearest-by-distance, `seed % catalog.length`).
 * All three are sensitive to catalog MEMBERSHIP, so appending cards to
 * BLOCK_DNA_LIBRARY silently re-resolves blocks a player already claimed —
 * changing their tactical layout, income, heat decay, cover, morale and
 * capacity on reload.
 *
 * Measured at the time batch two was written: 485 of 610 sampled generic
 * locations resolved to a DIFFERENT card once the catalog grew from 25 to 33.
 *
 * The guarantee this file locks down: a block claimed under catalog v1 always
 * re-resolves to the same v1 result, no matter how large the live library
 * becomes. The goldens below were generated by running the pre-batch-two
 * resolver (origin/main-tL2525) and must never be edited to make a test pass.
 */

import { describe, it, expect } from 'vitest';
import {
  BLOCK_DNA_LIBRARY,
  CURRENT_RESOLVER_CATALOG_VERSION,
  RESOLVER_CATALOG_V1_IDS,
  getResolverCatalog,
} from '../../config/blockDNA';
import { resolveBlockDNA, resolveLegacyBlockDNA } from '../blockDNAResolver';

interface LegacyGolden {
  dnaId: string;
  zoneLayout: string[];
  incomeMultiplier: number;
  heatDecayMultiplier: number;
  globalCoverBonus: number;
  startingMorale: number;
  maxMembers: number;
  startingHeat: number;
  hotBlock: boolean;
}

const BATCH_TWO_IDS = [
  'signal-yard',
  'marina-cut',
  'sable-plaza',
  'orchard-row',
  'switchback-garage',
  'civic-arcade',
  'ridge-estates',
  'vernon-court',
];

/** Generic (non-curated) locations that exercise every keyword rule plus the
 *  no-keyword nearest-DNA path. */
const LEGACY_CASES: {
  key: string;
  lat: number;
  lng: number;
  address: string;
  golden: LegacyGolden;
}[] = [
  {
    key: 'tampa-boulevard',
    lat: 27.9506,
    lng: -82.4572,
    address: '4400 Sunrise Boulevard, Tampa, FL',
    golden: {
      dnaId: 'brownsville-court',
      zoneLayout: ['street', 'curb', 'alley', 'alley', 'storefront', 'alley', 'parking', 'rooftop'],
      incomeMultiplier: 0.7,
      heatDecayMultiplier: 1.5,
      globalCoverBonus: 0.12,
      startingMorale: 82,
      maxMembers: 5,
      startingHeat: 0,
      hotBlock: false,
    },
  },
  {
    key: 'austin-court',
    lat: 30.2672,
    lng: -97.7431,
    address: '19 Kestrel Court, Austin, TX',
    golden: {
      dnaId: 'ring-road-underpass',
      zoneLayout: ['street', 'curb', 'parking', 'alley', 'alley', 'storefront', 'parking', 'building'],
      incomeMultiplier: 0.98,
      heatDecayMultiplier: 1.26,
      globalCoverBonus: 0.21,
      startingMorale: 76,
      maxMembers: 7,
      startingHeat: 1,
      hotBlock: false,
    },
  },
  {
    key: 'denver-lane',
    lat: 39.7392,
    lng: -104.9903,
    address: '77 Willow Lane, Denver, CO',
    golden: {
      dnaId: 'canal-court',
      zoneLayout: ['street', 'curb', 'sidewalk', 'alley', 'alley', 'parking', 'building', 'rooftop'],
      incomeMultiplier: 0.82,
      heatDecayMultiplier: 1.42,
      globalCoverBonus: 0.19,
      startingMorale: 84,
      maxMembers: 6,
      startingHeat: 0,
      hotBlock: false,
    },
  },
  {
    key: 'seattle-way',
    lat: 47.6062,
    lng: -122.3321,
    address: '250 Harbor Way, Seattle, WA',
    golden: {
      dnaId: 'wynwood-warehouse',
      zoneLayout: ['street', 'curb', 'sidewalk', 'storefront', 'alley', 'alley', 'parking', 'building'],
      incomeMultiplier: 1.5,
      heatDecayMultiplier: 0.7,
      globalCoverBonus: 0.1,
      startingMorale: 60,
      maxMembers: 10,
      startingHeat: 2,
      hotBlock: true,
    },
  },
  {
    key: 'houston-yard',
    lat: 29.7604,
    lng: -95.3698,
    address: '12 Industrial Yard, Houston, TX',
    golden: {
      dnaId: 'hialeah-warehouse-row',
      zoneLayout: ['street', 'curb', 'parking', 'alley', 'alley', 'storefront', 'parking', 'building'],
      incomeMultiplier: 1.05,
      heatDecayMultiplier: 1.15,
      globalCoverBonus: 0.14,
      startingMorale: 68,
      maxMembers: 9,
      startingHeat: 1,
      hotBlock: false,
    },
  },
  {
    key: 'charleston-shore',
    lat: 32.7765,
    lng: -79.9311,
    address: '901 Ocean Shore Drive, Charleston, SC',
    golden: {
      dnaId: 'south-beach-ocean',
      zoneLayout: ['street', 'curb', 'sidewalk', 'storefront', 'storefront', 'sidewalk', 'curb', 'street'],
      incomeMultiplier: 2,
      heatDecayMultiplier: 0.5,
      globalCoverBonus: -0.05,
      startingMorale: 55,
      maxMembers: 8,
      startingHeat: 3,
      hotBlock: true,
    },
  },
  {
    key: 'phoenix-center',
    lat: 33.4484,
    lng: -112.074,
    address: '55 Center Plaza, Phoenix, AZ',
    golden: {
      dnaId: 'overtown-nw3',
      zoneLayout: ['street', 'curb', 'sidewalk', 'storefront', 'storefront', 'alley', 'parking', 'rooftop'],
      incomeMultiplier: 0.75,
      heatDecayMultiplier: 1.4,
      globalCoverBonus: 0.05,
      startingMorale: 80,
      maxMembers: 6,
      startingHeat: 0,
      hotBlock: false,
    },
  },
  {
    key: 'reno-lot',
    lat: 39.5296,
    lng: -119.8138,
    address: '8 Garage Lot Road, Reno, NV',
    golden: {
      dnaId: 'ring-road-underpass',
      zoneLayout: ['street', 'curb', 'parking', 'alley', 'alley', 'storefront', 'parking', 'building'],
      incomeMultiplier: 0.98,
      heatDecayMultiplier: 1.26,
      globalCoverBonus: 0.21,
      startingMorale: 76,
      maxMembers: 7,
      startingHeat: 1,
      hotBlock: false,
    },
  },
  {
    key: 'chicago-terrace',
    lat: 41.8781,
    lng: -87.6298,
    address: '300 Tower Terrace, Chicago, IL',
    golden: {
      dnaId: 'brickell-highrise',
      zoneLayout: ['street', 'curb', 'sidewalk', 'storefront', 'building', 'building', 'building', 'rooftop'],
      incomeMultiplier: 2.4,
      heatDecayMultiplier: 0.55,
      globalCoverBonus: 0.08,
      startingMorale: 62,
      maxMembers: 11,
      startingHeat: 2,
      hotBlock: true,
    },
  },
  {
    key: 'boise-no-keyword',
    lat: 43.615,
    lng: -116.2023,
    address: '1234 Quiet Rd, Boise, ID',
    golden: {
      dnaId: 'plantation-acres',
      zoneLayout: ['street', 'curb', 'parking', 'parking', 'parking', 'sidewalk', 'curb', 'rooftop'],
      incomeMultiplier: 0.95,
      heatDecayMultiplier: 1.6,
      globalCoverBonus: 0.04,
      startingMorale: 78,
      maxMembers: 7,
      startingHeat: 0,
      hotBlock: false,
    },
  },
];

function shape(resolved: ReturnType<typeof resolveBlockDNA>): LegacyGolden {
  return {
    dnaId: resolved.dna.id,
    zoneLayout: resolved.zoneLayout,
    incomeMultiplier: resolved.incomeMultiplier,
    heatDecayMultiplier: resolved.dna.heatDecayMultiplier,
    globalCoverBonus: resolved.dna.globalCoverBonus,
    startingMorale: resolved.startingMorale,
    maxMembers: resolved.maxMembers,
    startingHeat: resolved.startingHeat,
    hotBlock: resolved.dna.hotBlock,
  };
}

describe('frozen v1 resolver catalog', () => {
  it('holds exactly the 25 pre-batch-two cards', () => {
    expect(RESOLVER_CATALOG_V1_IDS).toHaveLength(25);
    expect(new Set(RESOLVER_CATALOG_V1_IDS).size).toBe(25);
    expect(getResolverCatalog('v1')).toHaveLength(25);
  });

  it('still resolves every frozen id against the live library', () => {
    const liveIds = new Set(BLOCK_DNA_LIBRARY.map((dna) => dna.id));
    const missing = RESOLVER_CATALOG_V1_IDS.filter((id) => !liveIds.has(id));
    expect(missing).toEqual([]);
  });

  it('excludes batch-two cards from the v1 pool', () => {
    const v1Ids = new Set(getResolverCatalog('v1').map((dna) => dna.id));
    for (const id of BATCH_TWO_IDS) expect(v1Ids.has(id)).toBe(false);
  });

  it('keeps batch-two cards reachable in the current catalog', () => {
    expect(CURRENT_RESOLVER_CATALOG_VERSION).toBe('v2');
    const liveIds = new Set(getResolverCatalog().map((dna) => dna.id));
    for (const id of BATCH_TWO_IDS) expect(liveIds.has(id)).toBe(true);
    expect(getResolverCatalog()).toHaveLength(BLOCK_DNA_LIBRARY.length);
  });

  it('does not shrink the v1 pool when the library grows', () => {
    expect(BLOCK_DNA_LIBRARY.length).toBeGreaterThan(getResolverCatalog('v1').length);
  });
});

describe('legacy resolution contract', () => {
  it.each(LEGACY_CASES)(
    'reproduces the pre-batch-two result for $key',
    ({ lat, lng, address, golden }) => {
      expect(shape(resolveBlockDNA(lat, lng, address, 'v1'))).toEqual(golden);
    },
  );

  it('resolveLegacyBlockDNA is the v1-pinned resolver', () => {
    for (const c of LEGACY_CASES) {
      expect(shape(resolveLegacyBlockDNA(c.lat, c.lng, c.address))).toEqual(
        shape(resolveBlockDNA(c.lat, c.lng, c.address, 'v1')),
      );
    }
  });

  it('reports the catalog version it resolved under', () => {
    const c = LEGACY_CASES[0];
    expect(resolveBlockDNA(c.lat, c.lng, c.address, 'v1').catalogVersion).toBe('v1');
    expect(resolveBlockDNA(c.lat, c.lng, c.address).catalogVersion).toBe('v2');
  });

  /**
   * Guard rail. If this ever fails, the expanded catalog stopped changing
   * generic resolution — at which point someone may be tempted to delete the
   * pinning. Do not. Re-derive the goldens instead and keep the versioning.
   */
  it('demonstrates that the live catalog WOULD move these blocks', () => {
    const moved = LEGACY_CASES.filter(
      (c) => resolveBlockDNA(c.lat, c.lng, c.address).dna.id !== c.golden.dnaId,
    );
    expect(moved.length).toBeGreaterThan(0);
  });
});
