#!/usr/bin/env python3
"""Materialize the safe Supabase CLI migration set for the world-proof target.

This utility never links a project, applies migrations, sets secrets, or calls a
remote API. It exists to make the required migration lineage inspectable and
reproducible before an operator performs the separately approved staging proof.
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

SCRIPT_PATH = Path(__file__).resolve()
SUPABASE_ROOT = SCRIPT_PATH.parent.parent
MANIFEST_PATH = SUPABASE_ROOT / "world-proof-manifest.json"

CONFIG_TEMPLATE = """# Generated by prepare_nonprod_world_proof.py.\n# Do not add a production project reference or credentials to this file.\nproject_id = \"dealt-slide-world-proof\"\n\n[db]\nmajor_version = 17\n\n[db.migrations]\nenabled = true\n\n[db.seed]\nenabled = false\n\n[functions.world-tick-ghost]\nverify_jwt = false\n"""


def load_manifest() -> dict:
    try:
        manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise RuntimeError(f"Cannot read {MANIFEST_PATH}: {error}") from error

    if manifest.get("schema") != 1:
        raise RuntimeError("Unsupported world-proof manifest schema.")
    if not manifest.get("canonical_migrations"):
        raise RuntimeError("The world-proof manifest has no canonical migrations.")
    return manifest


def validate(manifest: dict) -> list[str]:
    errors: list[str] = []
    targets: set[str] = set()
    source_sql: dict[str, str] = {}

    for entry in manifest["canonical_migrations"]:
        source = SUPABASE_ROOT / entry["source"]
        target = entry["target"]
        if not source.is_file():
            errors.append(f"Missing canonical migration: {source}")
        else:
            source_sql[entry["source"]] = source.read_text(encoding="utf-8")
        if not target.endswith(".sql") or not target[:14].isdigit():
            errors.append(f"Invalid deterministic target name: {target}")
        if target in targets:
            errors.append(f"Duplicate materialized migration target: {target}")
        targets.add(target)

    for legacy in manifest.get("excluded_legacy_migrations", []):
        source = SUPABASE_ROOT / legacy["source"]
        if not source.is_file():
            errors.append(f"Missing declared legacy migration: {source}")

    required = manifest.get("required_objects", {})
    master_entry = manifest["canonical_migrations"][0]
    master_sql = source_sql.get(master_entry["source"], "")
    for table in required.get("base_tables", []):
        if f"public.{table}" not in master_sql:
            errors.append(f"Master schema does not define required base table public.{table}")

    foundation_entry = next(
        (entry for entry in manifest["canonical_migrations"] if entry["source"].endswith("005_authoritative_world_foundation.sql")),
        None,
    )
    if foundation_entry is None:
        errors.append("Manifest does not include authoritative-world migration 005.")
    else:
        foundation_sql = source_sql.get(foundation_entry["source"], "")
        for table in required.get("authoritative_tables", []):
            if f"public.{table}" not in foundation_sql:
                errors.append(f"Foundation migration does not define public.{table}")

    authoritative_sql = "\n".join(source_sql.values())
    for function in required.get("authoritative_functions", []):
        if function not in authoritative_sql:
            errors.append(f"Canonical migration set does not define {function}")

    return errors


def materialize(manifest: dict, workspace: Path) -> None:
    if workspace.exists() and any(workspace.iterdir()):
        raise RuntimeError(f"Workspace must be empty: {workspace}")

    migrations_dir = workspace / "supabase" / "migrations"
    migrations_dir.mkdir(parents=True, exist_ok=True)
    (workspace / "supabase" / "config.toml").write_text(CONFIG_TEMPLATE, encoding="utf-8")
    (workspace / "README.md").write_text(
        "# Disposable DEALT/SLIDE World-Proof Workdir\n\n"
        "This workdir was generated from `backend/supabase/world-proof-manifest.json`. "
        "It is for an explicitly named preview, staging, development, or sandbox target only. "
        "Do not link it to production. Run `supabase db push --dry-run` before any approved remote push.\n",
        encoding="utf-8",
    )

    for entry in manifest["canonical_migrations"]:
        source = SUPABASE_ROOT / entry["source"]
        destination = migrations_dir / entry["target"]
        shutil.copyfile(source, destination)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--workspace",
        type=Path,
        help="Empty destination directory where a disposable Supabase CLI workdir will be materialized.",
    )
    parser.add_argument(
        "--validate-only",
        action="store_true",
        help="Validate the manifest and source migrations without writing files.",
    )
    args = parser.parse_args()

    if bool(args.workspace) == bool(args.validate_only):
        parser.error("Choose exactly one of --workspace or --validate-only.")

    manifest = load_manifest()
    errors = validate(manifest)
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1

    if args.validate_only:
        print("World-proof manifest validation passed.")
        return 0

    materialize(manifest, args.workspace)
    print(f"Materialized disposable world-proof workdir: {args.workspace}")
    print("Next approved operator step: link only to the named non-production target, then run `supabase db push --dry-run`.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
