// ============================================================
// incomeEngine.ts - Passive income calculation engine
// Calculates income from dealers on blocks, factoring in
// street proximity, drug quality, member level, and heat
// ============================================================

import { STREET_PROXIMITY_TABLE } from '../types/slide.types';
import { getMemberHeatContribution } from '../utils/memberProgression';

export interface IncomeSource {
  memberId: string;
  memberName: string;
  blockId: string;
  role: 'dealer';
  level: number;
  streetProximity: number;  // Row index (0 = on street)
  drugType: string;
  drugTier: number;
  drugPurity: number;
  baseIncomePerHour: number;
}

export interface IncomeBreakdown {
  source: IncomeSource;
  grossIncome: number;
  proximityMultiplier: number;
  drugQualityMultiplier: number;
  levelMultiplier: number;
  heatPenalty: number;
  netIncome: number;
  heatGenerated: number;
  riskLevel: 'low' | 'medium' | 'high' | 'extreme';
}

export interface BlockIncomeReport {
  blockId: string;
  totalGrossIncome: number;
  totalNetIncome: number;
  totalHeatGenerated: number;
  dealers: IncomeBreakdown[];
  expenses: {
    salaries: number;
    maintenance: number;
    bribes: number;
  };
  profit: number;
}

// ============ INCOME CONSTANTS ============
export const INCOME_CONFIG = {
  BASE_INCOME_PER_HOUR: 50,      // Base $ per hour per dealer
  DRUG_TIER_MULTIPLIER: [1.0, 1.5, 2.5, 4.0, 8.0], // By tier 1-5
  PURITY_BONUS_FACTOR: 0.01,     // Per purity point above 50
  LEVEL_BONUS_PER_LEVEL: 0.02,   // 2% per level
  HEAT_PENALTY_FACTOR: 0.005,    // 0.5% income loss per heat point
  MAX_HEAT_PENALTY: 0.50,        // Max 50% income loss from heat
  SALARY_PER_LEVEL: 10,          // $ per hour per member level
  MAINTENANCE_PER_BLOCK: 25,     // $ per hour per block
  BRIBE_RATE: 0.05,              // 5% of income goes to bribes at high heat
  BRIBE_HEAT_THRESHOLD: 50,      // Bribes kick in above this heat
} as const;

// ============ INCOME FUNCTIONS ============

/**
 * Calculate income breakdown for a single dealer.
 */
export function calculateDealerIncome(
  source: IncomeSource,
  blockHeat: number
): IncomeBreakdown {
  // Base income
  const base = INCOME_CONFIG.BASE_INCOME_PER_HOUR;

  // Street proximity multiplier
  const proxEntry = STREET_PROXIMITY_TABLE[
    Math.min(source.streetProximity, STREET_PROXIMITY_TABLE.length - 1)
  ];
  const proximityMultiplier = proxEntry.incomeMultiplier;

  // Drug quality multiplier
  const tierMult = INCOME_CONFIG.DRUG_TIER_MULTIPLIER[source.drugTier - 1] ?? 1.0;
  const purityBonus = Math.max(0, source.drugPurity - 50) * INCOME_CONFIG.PURITY_BONUS_FACTOR;
  const drugQualityMultiplier = tierMult * (1 + purityBonus);

  // Level multiplier
  const levelMultiplier = 1 + source.level * INCOME_CONFIG.LEVEL_BONUS_PER_LEVEL;

  // Gross income
  const grossIncome = base * proximityMultiplier * drugQualityMultiplier * levelMultiplier;

  // Heat penalty
  const heatPenaltyRate = Math.min(
    INCOME_CONFIG.MAX_HEAT_PENALTY,
    blockHeat * INCOME_CONFIG.HEAT_PENALTY_FACTOR
  );
  const heatPenalty = grossIncome * heatPenaltyRate;

  // Net income
  const netIncome = grossIncome - heatPenalty;

  // Heat generated by this dealer
  const memberHeat = getMemberHeatContribution(source.level);
  const drugHeat = source.drugTier * 0.5;
  const proximityHeat = (1 - source.streetProximity / 7) * 2; // Closer to street = more heat
  const heatGenerated = memberHeat + drugHeat + proximityHeat;

  // Risk assessment
  const hitChance = proxEntry.hitChance;
  const riskLevel: 'low' | 'medium' | 'high' | 'extreme' =
    hitChance < 0.2 ? 'low' :
    hitChance < 0.5 ? 'medium' :
    hitChance < 0.8 ? 'high' : 'extreme';

  return {
    source,
    grossIncome: Math.round(grossIncome * 100) / 100,
    proximityMultiplier,
    drugQualityMultiplier: Math.round(drugQualityMultiplier * 100) / 100,
    levelMultiplier: Math.round(levelMultiplier * 100) / 100,
    heatPenalty: Math.round(heatPenalty * 100) / 100,
    netIncome: Math.round(netIncome * 100) / 100,
    heatGenerated: Math.round(heatGenerated * 100) / 100,
    riskLevel,
  };
}

/**
 * Calculate total income report for a block.
 */
export function calculateBlockIncome(
  blockId: string,
  dealers: IncomeSource[],
  blockHeat: number,
  totalMemberLevels: number
): BlockIncomeReport {
  const dealerBreakdowns = dealers.map(d => calculateDealerIncome(d, blockHeat));

  const totalGross = dealerBreakdowns.reduce((sum, d) => sum + d.grossIncome, 0);
  const totalNet = dealerBreakdowns.reduce((sum, d) => sum + d.netIncome, 0);
  const totalHeat = dealerBreakdowns.reduce((sum, d) => sum + d.heatGenerated, 0);

  // Expenses
  const salaries = totalMemberLevels * INCOME_CONFIG.SALARY_PER_LEVEL;
  const maintenance = INCOME_CONFIG.MAINTENANCE_PER_BLOCK;
  const bribes = blockHeat > INCOME_CONFIG.BRIBE_HEAT_THRESHOLD
    ? totalNet * INCOME_CONFIG.BRIBE_RATE
    : 0;

  const totalExpenses = salaries + maintenance + bribes;
  const profit = totalNet - totalExpenses;

  return {
    blockId,
    totalGrossIncome: Math.round(totalGross * 100) / 100,
    totalNetIncome: Math.round(totalNet * 100) / 100,
    totalHeatGenerated: Math.round(totalHeat * 100) / 100,
    dealers: dealerBreakdowns,
    expenses: {
      salaries: Math.round(salaries * 100) / 100,
      maintenance: Math.round(maintenance * 100) / 100,
      bribes: Math.round(bribes * 100) / 100,
    },
    profit: Math.round(profit * 100) / 100,
  };
}

/**
 * Calculate total income across all blocks.
 */
export function calculateTotalIncome(blockReports: BlockIncomeReport[]): {
  totalProfit: number;
  totalHeat: number;
  bestBlock: string | null;
  worstBlock: string | null;
} {
  if (blockReports.length === 0) {
    return { totalProfit: 0, totalHeat: 0, bestBlock: null, worstBlock: null };
  }

  const totalProfit = blockReports.reduce((sum, b) => sum + b.profit, 0);
  const totalHeat = blockReports.reduce((sum, b) => sum + b.totalHeatGenerated, 0);

  const sorted = [...blockReports].sort((a, b) => b.profit - a.profit);
  const bestBlock = sorted[0].blockId;
  const worstBlock = sorted[sorted.length - 1].blockId;

  return {
    totalProfit: Math.round(totalProfit * 100) / 100,
    totalHeat: Math.round(totalHeat * 100) / 100,
    bestBlock,
    worstBlock,
  };
}
